development:
  adapter: postgresql
  encoding: unicode
  database: be_assessment
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: be_assessment_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DB_URL"] %>
